XOR
northwesternmutual/regent pull request #13
Opened 2018-05-08 18:38 UTC by mrwatts88

Add the ability to evaluate rules composed with XOR, and the helper function, similar to and, or, not.

2018-05-08 21:08 UTC, eisenivan requested changes
Thanks so much for the PR. We're taking a look at it and will be in touch, but in the mean time I left a few notes.

Could you add unit tests for `index.js`, and `parse-composed.js`? There are `.spec.js` files as siblings to both with a bunch of examples.

How did you stumble on regent? Hope you don't mind me asking.

2018-05-08 21:08 UTC, eisenivan commented on src/impl.spec.js
> +  const WET_BUT_NOT_TOO_WET = xor(IS_RAINING, IS_SNOWING);
Love the example!

2018-05-08 21:08 UTC, eisenivan commented on src/index.js
> +export const xor = (...rules) => ({
We will probably want a test or two making sure that this function exists, and that checks it's param signature. So something like 

```
assert.equal(typeof xor, 'function')
```

2018-05-08 21:08 UTC, eisenivan commented on src/private/parse-composed.js
> +    const fxn = rule => (
This is great too! Nice abstraction.

2018-05-09 13:45 UTC, mrwatts88 commented
I will look into those changes today. I was browsing the Milwaukee Slack channel and I'll be interning at NWM this Summer so Regent caught my eye.

2018-05-09 14:08 UTC, eisenivan commented
Awesome! We are also considering caping the number of arguments `xor` gets to 2. We were initially thinking that it should take `n` arguments, and confirm that some but not all are true, like you implemented, but now we think it would be more clear if it took exactly 2 and threw an error if you passed it more.

Do you have any thoughts on that? I'd love to get some outside thinking on it.

2018-05-09 14:34 UTC, mrwatts88 commented
It's hard to say, but the way I've implemented it isn't typically the way XOR works with multiple inputs. In a digital logic sense, it typically outputs true if the number of true inputs is odd, false otherwise. So there are really 2 options for how to implement XOR with 3 or more arguments. Restricting the number of args to 2 will eliminate that ambiguity.

Tough call, but anyways I have added the tests you asked for. Let me know if you want to make the XOR change.

2018-05-14 14:56 UTC, eisenivan commented
@mrwatts88 this looks great! Only tests I'd like to see added would be sad path tests, so basically ensuring it throws an error when called with 0 rules, 1 rule, 3+ rules.

2018-05-15 03:25 UTC, mrwatts88 commented
@eisenivan okay I've added those tests. Let me know if they aren't in the correct place or if there is anything you need me to change.

2018-05-16 14:56 UTC, eisenivan approved these changes

2018-05-16 16:36 UTC, merged